<?php

// activation du module references
module_enable(array('menu_attributes'));

variable_set('menu_attributes_title_enable', '0');
variable_set('menu_attributes_id_enable', '0');
variable_set('menu_attributes_name_enable', '0');
variable_set('menu_attributes_rel_enable', '0');
variable_set('menu_attributes_class_enable', '0');
variable_set('menu_attributes_style_enable', '0');
variable_set('menu_attributes_target_enable', '1');
variable_set('menu_attributes_accesskey_enable', '0');
